<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Student extends Model
{
    protected $fillable = [
        'nip',
        'nis',
        'nisn',
        'nama_lengkap',
        'alamat',
        'jenis_kelamin',
        'no_kk',
        'nik',
        'tempat_lahir',
        'tanggal_lahir',
        'no_akte',
        'agama',
        'kewarganegaraan',
        'rt',
        'rw',
        'desa_kelurahan',
        'kecamatan',
        'kabupaten_kota',
        'provinsi',
        'kode_pos',
        'nama_ayah',
        'nik_ayah',
        'tahun_lahir_ayah',
        'pendidikan_ayah',
        'tahun_lulus_ayah',
        'pekerjaan_ayah',
        'nama_ibu',
        'nik_ibu',
        'tahun_lahir_ibu',
        'pendidikan_ibu',
        'tahun_lulus_ibu',
        'pekerjaan_ibu',
        'no_hp_telpon',
        'rombel_ads',
        'rombel_kelas',
        'sekolah_asal',
        'tahun_kelulusan',
        'no_peserta_un',
        'no_seri_ijazah',
        'no_skhun',
        'status_santri',
        'status_santri_other',
        'tanggal_masuk_pondok',
        'tinggi_badan',
        'berat_badan',
        'anak_ke',
        'jumlah_anak',
        'status_anak',
        'no_kks',
        'penerima_kps',
        'no_kps',
        'no_kip',
        'nama_di_kip',
        'terima_fisik',
        'kartu_jaminan',
        'email',
        'jenis_pendaftaran',
        'ket',
        'kelas_lama',
        'anbk'
    ];
}
